### PR TITLE
use #[no_main] and the entry! macro to specify the main function

### PR DESCRIPTION
**Pull request by danc86**
Matches cortex-m-rt. See:

https://github.com/rust-embedded/cortex-m-rt/pull/69
https://github.com/rust-embedded/cortex-m-rt/pull/78

### CODE REVIEW

**Comment by dvc94ch** [comment]
LGTM!

> Also unfortunately it means that the program crates have to depend directly on this crate now, to get the macro. But... 🤷

Have you tried `#![feature(rust_2018_preview)]` instead of `#[macro_use(entry)] extern crate riscv-rt`? [0]

- [0] https://rust-lang-nursery.github.io/edition-guide/2018/transitioning/modules/macros.html

**Comment by danc86** [comment]
Oooh interesting. I will take a look.

**Comment by dvc94ch** [comment]
@danc86 is this ok to merge?

**Comment by danc86** [comment]
Yep this one is good to go as is. We can always tweak the example to use the rust_2018_preview stuff later on.

**Pull request merged**
