### PR TITLE
Use inline assembly instead of pre-compiled blobs

### PR DESCRIPTION
**Pull request by romancardenas**
This PR substitutes pre-compiled blobs with inline assembly. This eases the build process and allows us to define custom runtime properties depending on the target or feature gates.

@onsdagens helped me with the linker script to ensure that `abort` is in the `text` section and avoid linker errors.

### CODE REVIEW

**Comment by romancardenas** [comment]
BTW, the blobs check is no longer required. We can remove that GH action once this PR is merged

**Comment by romancardenas** [comment]
Please, can someone from the @rust-embedded/riscv team take a look? I tested it on rather complex applications with RTIC and worked fine.

I think this "new" approach is worth it. Once we move to inline assembly, we can provide a set of features for additional functionalities (e.g., FPU initialization, a complete trap handler for atomic emulation, vectored mode...), following `cortex-m-rt` fashion. Please let me know what you think.

**Comment by almindor** [comment]
> Please, can someone from the @rust-embedded/riscv team take a look? I tested it on rather complex applications with RTIC and worked fine.
> 
> I think this "new" approach is worth it. Once we move to inline assembly, we can provide a set of features for additional functionalities (e.g., FPU initialization, a complete trap handler for atomic emulation, vectored mode...), following `cortex-m-rt` and `esp-rt` fashion. Please let me know what you think.

Hey, sorry about the delay, I've been pretty busy lately + vacation time. I'll try to go over this over the weekend.

**Comment by romancardenas** [comment]
Don't worry, just pinging in case the PR got buried in other duties, etc.

**Review by almindor — APPROVED** [review]
LGTM

**Comment by almindor** [comment]
Hmm I wonder how we can override the blobs check here, it seems github won't let us proceed.

**Pull request merged**
