### PR TITLE
Pass a0..a2 to main()

### PR DESCRIPTION
**Pull request by Disasm**
This PR delivers arguments stored in a0..a2 to `main`.

Fixes https://github.com/rust-embedded/riscv-rt/issues/92

Tested with:
* build the `empty` example for `riscv64imac-unknown-none-elf` with a memory file which puts everything to `0x80000000`
* run `qemu-system-riscv64 -nographic -machine virt -bios target/riscv64imac-unknown-none-elf/release/examples/empty -s -S`
* connect to qemu with gdb (`target remote :1234`)
* set breakpoint to main (`b main`)
* resume execution (`continue`)
* inspect registers (`info registers`)
```
a0             0x0	0
a1             0x87000000	2264924160
a2             0x1028	4136
```
* check header (`x/xw 0x87000000`)
```
0x87000000:	0xedfe0dd0
```

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’ve tested this in https://github.com/SimonSapin/riscv-qemu-demo, passing the second argument to [`Fdt::from_ptr`](https://docs.rs/fdt/0.1.3/fdt/struct.Fdt.html#method.from_ptr) works. Looks good to me.

**Review by almindor — APPROVED** [review]
lgtm

**Comment by almindor** [comment]
@Disasm @SimonSapin I forgot, we should add a CHANGELOG entry for this. Could any of you please make a PR for that?

**Comment by Disasm** [comment]
@almindor indeed, thank you! I created https://github.com/rust-embedded/riscv-rt/pull/96 to fix this.

**Pull request merged**
