### PR TITLE
Fix _start_trap address calculation

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by danc86** [comment]
Hmm. This patch is definitely closer to what we need... With `_start_trap as usize` which we have now, the `_start_rust` function tries loading from that address:

```
Dump of assembler code for function _start_rust:
   0x2040001c <+0>:	addi	sp,sp,-16
   0x2040001e <+2>:	sw	ra,12(sp)
   0x20400020 <+4>:	lui	a0,0x80000
   0x20400024 <+8>:	mv	a0,a0
   0x20400028 <+12>:	lui	a1,0x80000
   0x2040002c <+16>:	addi	a1,a1,4 # 0x80000004
   0x20400030 <+20>:	auipc	ra,0x2
   0x20400034 <+24>:	jalr	-746(ra) # 0x20401d46 <r0::zero_bss>
   0x20400038 <+28>:	j	0x2040003a <_start_rust+30>
   0x2040003a <+30>:	lui	a0,0x80000
   0x2040003e <+34>:	addi	a0,a0,4 # 0x80000004
   0x20400042 <+38>:	lui	a1,0x80000
   0x20400046 <+42>:	addi	a1,a1,4 # 0x80000004
   0x2040004a <+46>:	lui	a2,0x20402
   0x2040004e <+50>:	addi	a2,a2,520 # 0x20402208
   0x20400052 <+54>:	auipc	ra,0x2
   0x20400056 <+58>:	jalr	-698(ra) # 0x20401d98 <r0::init_data>
   0x2040005a <+62>:	j	0x2040005c <_start_rust+64>
   0x2040005c <+64>:	li	a0,0
=> 0x2040005e <+66>:	sb	a0,11(sp)
   0x20400062 <+70>:	lui	a1,0x20400
   0x20400066 <+74>:	lw	a1,158(a1) # 0x2040009e <_start_trap>
   0x2040006a <+78>:	sw	a0,4(sp)
   0x2040006c <+80>:	mv	a0,a1
   0x2040006e <+82>:	lw	a1,4(sp)
   0x20400070 <+84>:	auipc	ra,0x2
   0x20400074 <+88>:	jalr	-600(ra) # 0x20401e18 <riscv::register::mtvec::write>
   0x20400078 <+92>:	j	0x2040007a <_start_rust+94>
   0x2040007a <+94>:	auipc	ra,0x1
   0x2040007e <+98>:	jalr	-1624(ra) # 0x20400a22 <main>
   0x20400082 <+102>:	auipc	ra,0x0
   0x20400086 <+106>:	jalr	-106(ra) # 0x20400018 <abort>
End of assembler dump.
```

...which then traps. Took me a long time to figure out that my programs were immediately trapping to 0x0000_0000 because the code to set up the trap vector was broken... :-)

With this patch the `_start_rust` function looks better (passes the address of `_start_trap` instead of loading from it):

```
Dump of assembler code for function _start_rust:
   0x2040001c <+0>:	addi	sp,sp,-16
   0x2040001e <+2>:	sw	ra,12(sp)
   0x20400020 <+4>:	lui	a0,0x80000
   0x20400024 <+8>:	mv	a0,a0
   0x20400028 <+12>:	lui	a1,0x80000
   0x2040002c <+16>:	addi	a1,a1,4 # 0x80000004
   0x20400030 <+20>:	auipc	ra,0x2
   0x20400034 <+24>:	jalr	-746(ra) # 0x20401d46 <r0::zero_bss>
   0x20400038 <+28>:	j	0x2040003a <_start_rust+30>
   0x2040003a <+30>:	lui	a0,0x80000
   0x2040003e <+34>:	addi	a0,a0,4 # 0x80000004
   0x20400042 <+38>:	lui	a1,0x80000
   0x20400046 <+42>:	addi	a1,a1,4 # 0x80000004
   0x2040004a <+46>:	lui	a2,0x20402
   0x2040004e <+50>:	addi	a2,a2,520 # 0x20402208
   0x20400052 <+54>:	auipc	ra,0x2
   0x20400056 <+58>:	jalr	-698(ra) # 0x20401d98 <r0::init_data>
   0x2040005a <+62>:	j	0x2040005c <_start_rust+64>
   0x2040005c <+64>:	li	a0,0
   0x2040005e <+66>:	sb	a0,11(sp)
   0x20400062 <+70>:	lui	a1,0x20400
   0x20400066 <+74>:	addi	a1,a1,158 # 0x2040009e <_start_trap>
   0x2040006a <+78>:	sw	a0,4(sp)
   0x2040006c <+80>:	mv	a0,a1
   0x2040006e <+82>:	lw	a1,4(sp)
   0x20400070 <+84>:	auipc	ra,0x2
   0x20400074 <+88>:	jalr	-600(ra) # 0x20401e18 <riscv::register::mtvec::write>
   0x20400078 <+92>:	j	0x2040007a <_start_rust+94>
   0x2040007a <+94>:	auipc	ra,0x0
   0x2040007e <+98>:	jalr	1794(ra) # 0x2040077c <main>
   0x20400082 <+102>:	auipc	ra,0x0
   0x20400086 <+106>:	jalr	-106(ra) # 0x20400018 <abort>
End of assembler dump.
```

I noticed something odd though... once the program is running, gdb thinks that $mtvec is set to 0x2040_009c, not 0x2040_009e which is the address of `_start_trap`. Why is it 4 bytes less, and does it matter? I am just testing with the blinky_delay example which doesn't ever trap...

**Comment by Disasm** [comment]
@danc86 Thanks for pointing out!

RISC-V Privileged spec states that
> The value in the BASE field must always be aligned on a 4-byte boundary

so `0x2040_009c` is expected. However, for some reason `_start_trap` is not aligned.

I see two problems:
* there should be `.align 2` in [asm.S](https://github.com/rust-embedded/riscv-rt/blob/19251b88e56342a11a338c11620aa8406fc09a4f/asm.S#L39): `.align 4` aligns to 16-byte boundary.
* `.align` directive produces strange code.

```
.section .trap, "ax"
.align 2
.global _start_trap

_start_trap:
    mret
```
compiles to this:
```
test.o:     file format elf32-littleriscv


Disassembly of section .trap:

00000000 <_start_trap-0x2>:
   0:	0001                	nop

00000002 <_start_trap>:
   2:	30200073          	mret
```
And that's strange. As a workaround I suggest removing `.align` directive and forcing 4-byte section alignment in linker script.

**Comment by danc86** [comment]
Oh yes, it has to be 4-byte aligned because the 2 least significant bits are used as flags. Makes sense.

So I think it means this PR is good and we need a second one to fix the alignment of `_start_trap` as you suggest.

**Comment by Disasm** [comment]
bors r=danc86

**Pull request merged**
