### PR TITLE
Convert default_setup_interrupts into a Rust function

### PR DESCRIPTION
**Pull request by Disasm**
First step towards a fully inline-asm `riscv-rt`.

### CODE REVIEW

**Review by dkhayes117 — APPROVED** [review]
Lgtm

**Comment by dkhayes117** [comment]
Changelog entry?

**Comment by Disasm** [comment]
> Changelog entry?

I'm not sure what to add there. None of the changes are visible to user. I'll add an entry when I finish the asm->`global_asm!` transition.

**Comment by dkhayes117** [comment]
Okay, yes, that makes sense 👍

**Comment by dkhayes117** [comment]
Bors r+

**Pull request merged**
