### PR TITLE
Don't use a random hash ident, instead use the crate prefixed symbol

### PR DESCRIPTION
**Pull request by MabezDev**
This is what cortex-m land is doing. This was initially discovered to be an issue when implementing unwinding in riscv probe-rs, the dwarf info shows the hashed symbol name which is a bit weird, this makes it more clear what the symbol actually is.

### CODE REVIEW

**Review by almindor — DISMISSED** [review]

**Review by dkhayes117 — CHANGES_REQUESTED** [review]
Can you add an entry to the changlog.md  file?

**Comment by MabezDev** [comment]
Done :).

**Review by dkhayes117 — APPROVED** [review]
LGTM.  Thank you!

**Review by almindor — APPROVED** [review]

**Comment by noppej** [comment]
Thanks ... I can confirm that this fixes the stack unwind issue in `probe-rs` (unpublished PR at this point).

**Pull request merged**
