### PR TITLE
Add missing changelog entries

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Review by almindor — APPROVED** [review]

**Comment by SimonSapin** [comment]
Could you publish a new version on crates.io with this https://github.com/rust-embedded/riscv-rt/pull/95? Thanks!

**Comment by almindor** [comment]
@Disasm do you think this should be a minor or just patch bump?

**Comment by Disasm** [comment]
@almindor it should be a minor version since (according to changelog) `inline-asm` feature was removed.

**Comment by almindor** [comment]
released on crates.io

**Pull request merged**
