### PR TITLE
release v0.8.1

### LINKED ISSUE #85: New crates.io release
Would there be there any downsides to a new crates.io release with the latest changes on master?

### PR DESCRIPTION
**Pull request by almindor**
Release v0.8.1 to fix #85

### CODE REVIEW

**Review by Disasm — COMMENTED** [review]
Thanks! A few missing parts:
* A link for `[v0.8.1]` in changelog
* Update for the `[Unreleased]` link
* Update for version in Cargo.toml :)

**Comment by almindor** [comment]
> Thanks! A few missing parts:
> 
> * A link for `[v0.8.1]` in changelog
> * Update for the `[Unreleased]` link
> * Update for version in Cargo.toml :)

Done. Qq tho, do we push everything to master and tag then or do we tag code changes pre-release (e.g. before the changelog and cargo.toml) and tag before pushing the release?

**Comment by Disasm** [comment]
The general idea is to create a git tag for the commit that was released, so I usually do this after merging into master.

**Review by Disasm — APPROVED** [review]
LGTM,
bors r+

**Pull request merged**
