### PR TITLE
Add support for the riscv32i target

### PR DESCRIPTION
**Pull request by Disasm**
Ported from [fomu-rt](https://github.com/im-tomu/fomu-rt)

Closes: https://github.com/rust-embedded/riscv-rt/pull/34

### CODE REVIEW

**Comment by Disasm** [comment]
There are no tests on CI for this target because they require an unreleased-yet version of the `riscv` crate with riscv32i support.

**Comment by xobs** [comment]
Would it be possible to take `assemble.ps1` as well? It's kind of nice to work on both platforms.

Also, I've discovered that the CI tests don't seem to care which platform did the assembling.

Thanks for doing this, by the way!

**Comment by Disasm** [comment]
Added, thanks!

**Comment by Disasm** [comment]
Added CI rules and updated dependencies. I can't test this at the moment because I don't have any RISC-V hardware with me, but generated assembly for `riscv-rust-quickstart` looks sane. Seems like the latest `r0` doesn't have any major changes.

**Comment by Disasm** [comment]
I checked this PR with [icebreaker-litex-examples](https://github.com/icebreaker-fpga/icebreaker-litex-examples), works fine!

**Comment by Disasm** [comment]
Works for HiFive1 too.

**Comment by Disasm** [comment]
bors r=almindor

**Pull request merged**
