### PR TITLE
Implement interrupt and exception handling, bump version

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by Disasm** [comment]
Tested on FE310-G000 (HiFive1 board).

**Comment by almindor** [comment]
A bit busy atm. but I hope to do a test on my hifive1-revB tomorrow.

**Comment by almindor** [comment]
Having issues with RTC clock not causing the interrupts on my hifive1-revB but the board has USB issues so it might be "going". I'll re-test soon to see if it persists.

**Comment by almindor** [comment]
Works fine with latest versions, only issue I got was the memory fence not working on --release mode, but it's a different issue.

**Comment by Disasm** [comment]
I checked that this code works on K210 too.

**Comment by Disasm** [comment]
I was able to reproduce machine timer interrupt handling for GD32VF103. I have no idea how to handle external interrupts on this chip. Their interrupt handling scheme is quite strange, with non-standard CSRs involved.

**Comment by Disasm** [comment]
Fixed the conflicts with rebase

**Pull request merged**
