### PR TITLE
Add pre-Rust trap handler

### LINKED ISSUE #82: Pre initialization trap handling
At the moment, the trap handler is initialized rather late in the boot procedure (it is more or less the last thing to happen before jumping to `main`). However, traps may happen before this, and they will not be handled appropriately (as far as I can tell, my CPU lands in a reset loop).

The most prominent situation in which this may happen is when I accidentally run the software compiled with multiplication instructions on a machine without them, because of these lines: https://github.com/rust-embedded/riscv-rt/blob/master/asm.S#L99-L110

I see multiple different approaches to improve the current situation:

- Simply hardcode the non-mul branch in the `asm.S`. Since the factor against we are multiplying is rather low (it's the number of harts of the machine), the run time overhead shouldn't hit that hard.
- Going one step further, I suggest compiling `asm.S` for the `rv32i` and `rv64i` targets only. Most of these extensions aren't needed anyways during initialization.
- Alternatively, define a pre-Rust trap handler which is initialized first in `_start`. Once the Rust runtime is ready, `default_setup_interrupts` will override it to the actual implementation.

### PR DESCRIPTION
**Pull request by piegamesde**
Closes #82.

The trap handler is initialized as the first thing, even before jumping into `_abs_start`. The default trap initializer will jump to `_start_trap_pre_init` on a trap. By default, this symbol will be set to `abort` in the linker script.

This change is tested as in Works For Me™. I wanted to add some documentation about it but didn't really know where to put it.

### CODE REVIEW

**Review by almindor — APPROVED** [review]
LGTM

**Comment by Disasm** [comment]
This handler seems to be quite useless for Rust (and `riscv-rt` is a library for Rust) since it's called before memory and stack initialization. @piegamesde could you explain what problem you're trying to solve with this approach? From #82 I can only guess that you're trying to solve the "I used a wrong target" problem, but hopefully I'm wrong.

**Comment by piegamesde** [comment]
> since it's called before memory and stack initialization

That's exactly the point. Things may go wrong during initialization, and at the moment the hardware is not set up to handle this. Hardware may start breakdancing or go into a boot 
loop, whereas a controlled "bad state" is desired instead.

Accidentally using a wrong target is just my personal motivation, since that's the way I ran into the issue. However, there are many more failure scenarios where this may prove useful.

**Comment by Disasm** [comment]
If execution fails inside riscv-rt during initialization, then it's a bug in riscv-rt and should be fixed accordingly. I see the only good option for the additional handler you're trying to add: hardwire it to `abort`.

**Comment by piegamesde** [comment]
I just checked, and apparently the `mtvec` is kind of optional in the spec (it may at least be read-only). Thus, those running on minimal hardware will need the possibility to override the trap initializer.

**Comment by piegamesde** [comment]
So, what are the options to move this forward?

**Comment by Disasm** [comment]
I see two options: either setting `mtvec` to `abort` or closing the PR. I don't see any use in the current implementation. It just makes things more complex while solving a problem that shouldn't exist in the first place.

**Pull request closed without merging**
